version: '3.8'

services:
  app:
    image: mbonigabay/kigali-talent-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - EMAIL_USERNAME=username
      - EMAIL_ADDRESS=email
      - EMAIL_PASSWORD=password