version: '3.8'

services:
  app:
    image: mbonigabay/kigali-talent-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - EMAIL_USERNAME='Alayna Lesch'
      - EMAIL_ADDRESS='alayna.lesch@ethereal.email'
      - EMAIL_PASSWORD='xcuUbEdZN6DCUzbcB6'
      - JWT_SECRET='new-test-secret-for-debugging-12345'